-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 23, 2019 at 07:20 PM
-- Server version: 10.1.28-MariaDB
-- PHP Version: 7.0.24

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `asos`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `ID` int(255) NOT NULL,
  `Image` varchar(50) DEFAULT NULL,
  `Name` varchar(50) DEFAULT 'Unknown',
  `Brand` varchar(50) DEFAULT 'Unknown',
  `Price` int(6) DEFAULT '0',
  `Type` varchar(50) DEFAULT 'Unknown',
  `Gender` varchar(50) DEFAULT 'Unknown',
  `Fit` varchar(50) DEFAULT 'Unknown',
  `Colour` varchar(50) DEFAULT 'Unknown',
  `Style` varchar(50) DEFAULT 'Unknown',
  `Design` varchar(50) DEFAULT 'Unknown',
  `Material` varchar(50) DEFAULT 'Unknown',
  `Features` varchar(50) DEFAULT 'Unknown',
  `Intent` varchar(50) DEFAULT 'Unknown',
  `Weather` varchar(50) DEFAULT 'Unknown',
  `Season` varchar(50) DEFAULT 'Unknown',
  `Keywords` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`ID`, `Image`, `Name`, `Brand`, `Price`, `Type`, `Gender`, `Fit`, `Colour`, `Style`, `Design`, `Material`, `Features`, `Intent`, `Weather`, `Season`, `Keywords`) VALUES
(1, 'res/Products/Tops/MissguidedPlungePinkTop', 'Missguided tall plunge bodysuit in paisley print', 'Missguided', 2500, 'Top', 'Female', 'Bodycon', 'Pink', 'Bodysuit', 'Paisley', 'Polyester, Elastane', 'Long Sleeve, Plunge neck, Wrap front, Bell sleeves', 'Casual, Evening, Outerwear', 'Warm, Cloudy, Sunny', 'Spring, Summer', 'New-In'),
(2, 'res/Products/Tops/StradOversizedWhiteTop', 'Stradivarius oversized t-shirt in white', 'Stradivarius', 799, 'Top', 'Female', 'Oversized', 'White', 'Tshirts', 'Plain', 'Cotton, Elastane', 'Short sleeve, Crew neck', 'Casual, Everyday, Lazy', 'Sunny, Cloudy, Warm', 'Spring, Summer', 'New-In'),
(3, 'res/Products/Tops/ASOSLongSleeveSequin', 'ASOS DESIGN tall long sleeve top with sequin embel', 'ASOS DESIGN', 3800, 'Top', 'Female', 'Regular', 'Gold', 'Top', 'Sequin', 'Polyester', 'Long sleeve, Round neck, Sequins', 'Evening, Outerwear', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'Null'),
(4, 'res/Products/Tops/ASOSDottedTop', 'ASOS DESIGN oversized t-shirt with iridescent crys', 'ASOS DESIGN', 2500, 'Top', 'Female', 'Relaxed', 'White', 'Tshirts', 'Studded', 'Cotton', 'Crew neck, short sleeve', 'Evening, Outerwear, Casual', 'Warm, Sunny', 'Spring, Summer, Autumn', 'NULL'),
(5, 'res/Products/Tops/CollusionHighNeckCrop', 'COLLUSION high neck crop top', 'COLLUSION', 500, 'Top', 'Female', 'Bodycon', 'Yellow', 'Top', 'Plain', 'Viscose, Elastane', 'Crop, High neck', 'Casual, Everyday, Outerwear', 'Sunny, Warm', 'Spring, Summer', 'New-In'),
(6, 'res/Products/Tops/PLTPinkLongSleeve', 'PrettyLittleThing exclusive peplum blouse in pink ', 'PrettyLittleThing', 2000, 'Top', 'Female', 'Regular', 'Pink', 'Blouse', 'Polka dot', 'Polyester', 'V neck, Faux button placket, Ruffle hem, Zip back ', 'Casual, Everyday, Outerwear', 'Cloudy, Sunny, Warm', 'Spring, Summer, Autumn', NULL),
(10, 'res/Products/Tops/ASOSLongSleeveBlackSatin', 'ASOS DESIGN relaxed satin long sleeve shirt', 'ASOS DESIGN', 2800, 'Top', 'Female', 'Relaxed', 'Black', 'Shirt', 'Plain', 'Polyester', 'Notch collar, Long sleeve, Buttons placket', 'Outerwear, Formal, evening, everyday, casual', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(11, 'res/Products/Tops/LevisPerfectTop', 'Levi\'s perfect t-shirt with batwing logo', 'Levis', 2000, 'Top', 'Female', 'Regular', 'White', 'Tshirts', 'Logo', 'Cotton', 'Round neck', 'Casual, Everyday, Lazy', 'sunny, warm', 'Spring, Summer, Autumn', 'NULL'),
(12, 'res/Products/Tops/JDYGreenLaceTop', 'JDY lace cami top in green', 'JDY', 1400, 'Top', 'Female', 'Regular', 'Green', 'Top', 'Lace', 'Polyester', 'Cami straps, lace trim', 'Casual, Everyday', 'Sunny, Warm', 'Summer', 'NULL'),
(17, 'res/Products/Tops/ASOSBandeauWhite', 'ASOS DESIGN bandeau body in white', 'ASOS DESIGN', 1000, 'Top', 'Female', 'Bodycon', 'White', 'Top', 'Bandeau', 'Cotton, Elastane', 'Press stud fastening, sleeveless', 'Everyday, Casual, Outerwear', 'Sunny, Warm', 'Summer', NULL),
(18, 'res/Products/Tops/Pull&BearBoxyShirtGreen', 'Pull&Bear boxy shirt in green tropical print', 'PullAndBear', 1799, 'Top', 'Female', 'Relaxed', 'Green', 'Boy Shirt', 'Tropical Print', 'Viscose', 'Notch lapel, Buttons, Curved hem, Cropped', 'Everyday, Casual', 'Sunny, Warm', 'Spring, Summer', 'New-In'),
(21, 'res/Products/Tops/ASOSYellowWrapTop', 'ASOS DESIGN wrap top with cape back detail', 'ASOS DESIGN', 2800, 'Top', 'Female', 'Regular', 'Yellow', 'Top', 'Plain', 'Polyester', 'V neck, Wrap front, Tie side, Ruffle trims', 'Outerwear', 'Warm, Sunny, Cloudy', 'Spring, Summer', 'NULL'),
(24, 'res/Products/Tops/PLTFestivalTop', 'PrettyLittleThing festival crop top co-ord in rain', 'PrettyLittleThing', 2200, 'Top', 'Female', 'Regular', 'Multi', 'Top', 'Rainbow, Sequin', 'Polyester', 'Round neck, Rainbow stripe, Cropped', 'Festival, Everyday, Outerwear', 'Sunny, Warm', 'Summer', 'NULL'),
(25, 'res/Products/Tops/PLTCoordBralet', 'PrettyLittleThing Co-ord beach bralet in geo print', 'PrettyLittleThing', 1800, 'Top', 'Female', 'Regular', 'Multi', 'Bralet', 'Geo Print', 'Polyester', 'Triangle cups, Bold Print, Stretch back', 'Everyday, Casual, Beach', 'Sunny, Warm', 'Summer', 'NULL'),
(26, 'res/Products/Tops/RoseHeartTop', 'Wednesday\'s Girl relaxed t-shirt with rose heart', 'Wednesdays Girl', 1200, 'Top', 'Female', 'Relaxed', 'White', 'Tshirts', 'Print', 'Polyester, Cotton', 'Crew neck, Short sleeve, Rose heart print', 'Casual, Everyday', 'Sunny, Warm', 'Spring, Summer', 'NULL'),
(27, 'res/Products/Tops/EspiritPoloStriped', 'Espirit polo with vertical stripe', 'Espirit', 1900, 'Top', 'Male', 'Regular', 'Navy', 'Polo', 'Stripe', 'Cotton', 'Chest pockets, Short sleeve', 'Casual, Everyday, Outerwear', 'Sunny, Warm', 'Spring, Summer', 'NULL'),
(28, 'res/Products/Tops/ASOSMusclePolo', 'ASOS DESIGN muscle fit polo in jersey', 'ASOS DESIGN', 1000, 'Top', 'Male', 'Muscle', 'Indigo', 'Polo', 'Plain', 'Polyester, Cotton, Elastane', 'Collar, Buttons Placket, Fitted Cuffs', 'Everyday, Casual', 'Sunny, Warm', 'Spring, Summer', 'NULL'),
(29, 'res/Products/Tops/ASOSLongSleevePolo', 'ASOS DESIGN long sleeve polo shirt with zip neck i', 'ASOS DESIGN', 2200, 'Top', 'Male', 'Regular', 'Navy', 'Long Sleeve Polo', 'Ribbed', 'Cotton, Polyester, Elastane', 'Ribbed finish, Collar, Zip placket, Fitted cuffs', 'Casual, Everyday, Outerwear', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(30, 'res/Products/Tops/PumaGolfPolo', 'Puma Golf Rotation polo in Navy 57787503', 'Puma', 3500, 'Top', 'Male', 'Regular', 'Navy', 'Polo', 'Logo', 'Polyester', 'Collar, Buttons, Split sides, Fitted cuffs', '\r\n Active', 'Sunny, Warm', 'Summer', 'Active'),
(31, 'res/Products/Tops/ASOSLongSleevePoloHeritage', 'ASOS DESIGN relaxed long sleeve polo with all over', 'ASOS DESIGN', 1800, 'Top', 'Male', 'Relaxed', 'Teal blue', 'Long Sleeve Polo', 'Print', 'Cotton', 'Collar, Buttons, Long sleeve', 'Everyday, Casual', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'Null'),
(32, 'res/Products/Tops/ReplayPatternedShortShirt', 'Replay revered collar short sleeve shirt in multi', 'Replay', 8500, 'Top', 'Male', 'Regular', 'Multi', 'Short Sleeve Shirt', 'Print', 'Cotton', 'Bold print, Revere collar, Buttons, Pockets', 'Everyday, Casual, Beach, Outerwear', 'Sunny, Warm', 'Spring, Summer', 'NULL'),
(33, 'res/Products/Tops/NewLookWhiteFormalShirt', 'New Look poplin shirt in regular fit in white', 'New Look', 1299, 'Top', 'Male', 'Regular', 'White', 'Shirt', 'Plain', 'Polyester, Cotton', 'Point Collar, Buttons placket', 'Formal, Outerwear', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(34, 'res/Products/Tops/ASOSSlimCheckShirtRed', 'ASOS DESIGN stretch slim check shirt with acid was', 'ASOS DESIGN', 1100, 'Top', 'Male', 'Slim', 'Red', 'Shirt', 'Check', 'Cotton, Elastane', 'Button down collar, Long Sleeve', 'Casual, Everyday, Outerwear', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(35, 'res/Products/Tops/ASOSPaisleyShirt', 'ASOS DESIGN regular fit navy paisley shirt', 'ASOS DESIGN', 1100, 'Top', 'Male', 'Regular', 'Navy', 'Shirt', 'Print', 'Vicose', 'Bold print, Spread collar, Buttons, Long sleeve', 'Outerwear, Everyday, Casual', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(36, 'res/Products/Tops/ASOSShirtMidBlue', 'ASOS DESIGN slim fit shirt with in mid blue', 'ASOS DESIGN', 2000, 'Top', 'Male', 'Slim', 'Mid blue', 'Shirt', 'Plain', 'Cotton, Elastane', 'Point collar, Buttons placket', 'Formal, Casual, Everyday, Outerwear', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(37, 'res/Products/Tops/SikSilkRingerTshirt', 'SikSilk ringer t-shirt in beige', 'SikSilk', 3000, 'Top', 'Male', 'Slim', 'Beige', 'Ringer Tshirt', 'Logo', 'Polyester, Elastane', 'Crew neck, Curved hem', 'Casual, Everyday', 'Sunny, Warm', 'Spring, Summer, Autumn', 'NULL'),
(38, 'res/Products/Tops/CelioBasicVest', 'Celio basic vest in white', 'Celio', 800, 'Top', 'Male', 'Regular', 'White', 'Vest', 'Plain', 'Cotton', 'Crew neck, Sleeveless', 'Casual, Everyday', 'Sunny, Warm', 'Summer', 'NULL'),
(39, 'res/Products/Tops/LevisBatwingTshirt', 'Levi\'s t-shirt batwing logo', 'Levis', 2000, 'Top', 'Male', 'Regular', 'White', 'Tshirts', 'Logo', 'Cotton', 'Crew neck, Short sleeve', 'Casual, Everyday', 'sunny, warm', 'Spring, Summer, Autumn', 'NULL'),
(40, 'res/Products/Tops/TimberlandPrintTshirt', 'Timberland crew neck t-shirt with print in cut and', 'Timberland', 2500, 'Top', 'Male', 'Regular', 'Black', 'Tshirts', 'Print, Logo', 'Cotton', 'Crew neck, Short sleeve, Contrast panel', 'Casual, Everyday', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn', 'NULL'),
(41, 'res/Products/Tops/TommyLongTshirt', 'Tommy Hilfiger crew neck long sleeve t-shirt with ', 'Tommy Hilfiger', 3200, 'Top', 'Male', 'Regular', 'Grey', 'Long Sleeve Tshirt', 'Print, Logo', 'Cotton', 'Crew neck, Long sleeve', 'Casual, Everyday, Lazy', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(42, 'res/Products/Jumpers/AdidasWhiteHoodie', 'Adidas Originals adicolor cropped hoodie in white', 'Adidas', 4500, 'Jumper', 'Female', 'Relaxed', 'White', 'Hoodie', 'Stripe, Logo', 'Cotton', 'Long sleeve, Drawstring hood, Dropped shoulders', 'Lazy', 'Cold, Cloudy', 'Spring, Summer, Autumn, Winter', 'Active'),
(43, 'res/Products/Jumpers/NikeLeopardSweatshirt', 'Nike Leopard Print Sweatshirt', 'Nike', 5000, 'Jumper', 'Female', 'Relaxed', 'Desert Ochre Brown', 'Sweatshirt', 'Print, Logo', 'Cotton, Polyester', 'Crew neck, Fitted cuffs and hem, Baggy', 'Casual, Everyday, Lazy', 'Cold, Cloudy', 'Spring, Summer, Autumn, Winter', 'NULL'),
(44, 'res/Products/Jumpers/PoloStripedSweatshirt', 'Polo Ralph Lauren stripe teddy sweatshirt', 'Polo Ralph Lauren', 13500, 'Jumper', 'Female', 'Relaxed', 'White', 'Sweatshirt', 'Stripe', 'Cotton, Polyester', 'Crew neck, Printed front', 'Casual, Everyday, Lazy', 'Cold, Cloudy', 'Spring, Summer, Autumn, Winter', 'NULL'),
(45, 'res/Products/Jumpers/NAKDBlockSweatshirt', 'Na-kd colour block sweatshirt in beige', 'NAKD', 3800, 'Jumper', 'Female', 'Regular', 'Beige', 'Sweatshirt', 'Colour block', 'Cotton', 'Crew neck', 'Casual, Everyday, Lazy', 'Cold, Cloudy', 'Spring, Summer, Autumn, Winter', 'NULL'),
(46, 'res/Products/Jumpers/PimkieRedHoodie', 'Pimkie hoodie in red', 'Pimkie', 1399, 'Jumper', 'Female', 'Regular', 'Red', 'Hoodie', 'Plain', 'Polyester, Cotton', 'Drawstring hoood, Dropped shoulders, Ribbed cuffs', 'Casual, Everyday, Lazy', 'Cold, Cloudy', 'Spring, Summer, Autumn, Winter', 'NULL'),
(47, 'res/Products/Jumpers/HollisterStripeHoodie', 'Hollister hoodie in stripe', 'Hollister', 2900, 'Jumper', 'Female', 'Relaxed', 'White', 'Hoodie', 'Stripe, Logo', 'Cotton, Polyester', 'Drawstring hood, Pouch pockets, Baggy', 'Casual, Everyday, Lazy', 'Cold, Cloudy', 'Spring, Summer, Autumn, Winter', 'NULL'),
(48, 'res/Products/Jumpers/BershkaTieDieHoodie', 'Bershka hoodie in tie die', 'Bershka', 1999, 'Jumper', 'Female', 'Relaxed', 'Blue, pink, purple', 'Hoodie', 'Tie Die', 'Cotton, Polyester', 'Drawstring hood, Dropped shoulders, Pouch pockets,', 'Casual, Everyday, Lazy', 'Cold, Cloudy', 'Spring, Summer, Autumn, Winter', 'NULL'),
(49, 'res/Products/Jumpers/PimkieRedCardigan', 'Pimkie lightweight cardigan in red', 'Pimkie', 1699, 'Jumper', 'Female', 'Regular', 'Red', 'Cardigan', 'Plain', 'Acrylic, Cotton', 'Round neck, Buttons placket', 'Casual, Outerwear, Everyday', 'Warm, Sunny, Cloudy', 'Spring, Summer, Autumn', 'NULL'),
(50, 'res/Products/Jumpers/ASOSPinkJumper', 'ASOS DESIGN square neck stitch detail jumper with ', 'ASOS DESIGN', 2800, 'Jumper', 'Female', 'Regular', 'Pink', 'Jumper', 'Stitch', 'Acrylic', 'Sqaure neck, Ruffle overlay, Ribbed trims', 'Casual, Everyday, Lazy', 'Cold, Cloudy', 'Spring, Summer, Autumn, Winter', 'NULL'),
(51, 'res/Products/Jumpers/MangoKnittedJumper', 'Mango knitted jumper with tie co-ord', 'Mango', 3999, 'Jumper', 'Female', 'Relaxed', 'Beige', 'Jumper', 'Plain', 'Acrylic, Polyester', 'Crew neck, Long sleeve, Dropped shoulders, Tie hem', 'Casual, Lazy, Everyday, Lazy', 'Cloudy, Cold', 'Spring, Summer, Autumn, Winter', 'NULL'),
(52, 'res/Products/Jumpers/YASBaggyJumper', 'Y.A.S chunky v neck stripe jumper', 'YAS', 5500, 'Jumper', 'Female', 'Oversized', 'Multi', 'Jumper', 'Strip', 'Acrylic, Nylon, Polyester', 'V neck, Dropped shoulders, Ribbed finish, cuffs', 'Casual, Everyday, Lazy', 'Cold, Cloudy', 'Spring, Summer, Autumn, Winter', 'NULL'),
(53, 'res/Products/Jumpers/ASOSChunkyCardiganRed', 'ASOS DESIGN chunky cardigan in moving rib with sta', 'ASOS DESIGN', 3200, 'Jumper', 'Female', 'Relaxed', 'Cinnamon', 'Cardigan', 'Ribbed', 'Acrylic, Polyester', 'Buttons, Dropped shoulders, Ribbed finish', 'Casual, Everyday, Lazy', 'Cloudy, Cold', 'All', 'NULL'),
(54, 'res/Products/Jumpers/BoohooOversizedJumper', 'Boohoo exclusive basic oversized v neck jumper in ', 'Boohoo', 1500, 'Jumper', 'Female', 'Oversized', 'Blue', 'Jumper', 'Plain', 'Acrylic', 'V neck, Dropped shoulders, Ribbed trims', 'Lazy, Casual, Everyday', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'All', 'NULL'),
(55, 'res/Products/Jumpers/ASOSStitchedBrightJumper', 'ASOS DESIGN flared sleeve stitch detail jumper', 'ASOS DESIGN', 2600, 'Jumper', 'Female', 'Slim', 'Green', 'Jumper', 'Open stitch', 'Acrylic', 'Frill neck, Flared ribbed sleeves', 'Outerwear, Casual, Festival', 'Warm, Cloudy, Sunny', 'Spring, Summer', 'NULL'),
(56, 'res/Products/Jumpers/LipsyLonglineCardigan', 'Lipsy longline printed cardigan in multi', 'Lipsy', 3500, 'Jumper', 'Female', 'Regular', 'Multi', 'Cardigan', 'Print', 'Acrylic, Nylon', 'Plunge front, Tie waist, Longline style', 'Everyday, Casual, Lazy', 'Cold, Cloudy', 'All', 'NULL'),
(57, 'res/Products/Jumpers/AllSaintsGreyHoodie', 'AllSaints hoodie in charcoal', 'AllSaints', 7500, 'Jumper', 'Male', 'Regular', 'Grey', 'Hoodie', 'Logo', 'Cotton, Polyester', 'Drawstring hood, Side pockets, Fitted trims', 'Casual, Everyday, Lazy', 'Cold, Cloudy', 'All', 'NULL'),
(58, 'res/Products/Jumpers/TimberlandGreySweatshirt', 'Timberland crew neck sweatshirt with print in grey', 'Timberland', 5500, 'Jumper', 'Male', 'Regular', 'Grey', 'Sweatshirt', 'Print, Logo', 'Cotton, Polyester', 'Crew neck, Ribbed trims', 'Casual, Everyday, Active', 'Cloudy, Cold', 'All', 'NULL'),
(59, 'res/Products/Jumpers/NikeBlackZipHoodie', 'Nike Club zip-up hoodie in black 804389-010', 'Nike', 4800, 'Jumper', 'Male', 'Regular', 'Black', 'Hoodie', 'Logo', 'Cotton, Polyester', 'Funnel neck, Drawstring hood, Zip opening, pockets', 'Active, Casual', 'Sunny, Warm, Cold, Windy, Wet, Cloudy', 'Spring, Summer, Autumn, Winter', 'NULL'),
(60, 'res/Products/Jumpers/VansMultiSweatshirt', 'Vans colour block sweatshirt in white', 'Vans', 4400, 'Jumper', 'Male', 'Regular', 'White', 'Sweatshirt', 'Colour block', 'Cotton', 'crew neck, Fitted trims, Long sleeve', 'Outerwear, Casual, Festival, Active', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(61, 'res/Products/Jumpers/BossShortHoodie', 'BOSS Bodywear short sleeve logo hoodie in black', 'BOSS', 6900, 'Jumper', 'Male', 'Regular', 'Black', 'Short Sleeve Hoodie', 'Print, Logo', 'Cotton', 'Drawstring hood, Short sleeve', 'Active', 'Windy, Cloudy, Warm', 'Spring, Summer, Autumn', 'NULL'),
(62, 'res/Products/Jumpers/ASOSPinkSplitHoodie', 'ASOS DESIGN oversized hoodie with step hem in pink', 'ASOS DESIGN', 2200, 'Jumper', 'Male', 'Oversized', 'Pink', 'Hoodie', 'Plain', 'Cotton', 'Drawstring hood, Dropped shoulders, Pouch pocket, ', 'Active, Lazy, Casual', 'Wet, Windy, Cold, Cloudy', 'Spring, Summer, Autumn, Winter', 'NULL'),
(63, 'res/Products/Jumpers/ASOSGreyBomber', 'ASOS DESIGN jersey bomber in light grey', 'ASOS DESIGN', 2000, 'Jumper', 'Male', 'Regular', 'Harbour mist white', 'Jersey bomber', 'Plain', 'Cotton', 'Baseball collar, Zip fastening, Ribbed trims', 'Active, Casual', 'Sunny, Warm, Cold, Windy, Cloudy', 'Spring, Summer, Autumn, Winter', 'NULL'),
(64, 'res/Products/Jumpers/PoloStripedJumper', 'Polo Ralph Lauren crest logo stripe cotton knit ju', 'Polo Ralph Lauren', 17500, 'Jumper', 'Male', 'Regular', 'Multi', 'Jumper', 'Stripe', 'Cotton', 'Crew neck, Ribbed trims', 'Casual, Outerwear', 'Cold, Cloudy', 'All', 'NULL'),
(65, 'res/Products/Jumpers/ASOSGreyMuscleJumper', 'ASOS DESIGN muscle fit lightweight cable jumper in', 'ASOS DESIGN', 2500, 'Jumper', 'Male', 'Muscle', 'Grey', 'Jumper', 'Cable', 'Cotton, Acrylic', 'Crew neck, Fitted trims', 'Casual, Outerwear', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'All', 'NULL'),
(66, 'res/Products/Jumpers/WeekdayWhiteJumper', 'Weekday Ted rib turtleneck in white', 'Weekday', 1800, 'Jumper', 'Male', 'Regular', 'White', 'Turtleneck', 'Plain', 'Cotton, Elastane', 'Turtle neck', 'Casual, Outerwear', 'Cold, Cloudy', 'Winter, Autumn, Spring', 'NULL'),
(67, 'res/Products/Jumpers/CollusionStripedShortJumper', 'COLLUSION striped short sleeve jumper', 'COLLUSION', 1800, 'Jumper', 'Male', 'Relaxed', 'Multi', 'Jumper', 'Stripe', 'Cotton', 'Crew neck, Dropped shoulders', 'Casual, Everyday', 'Sunny, Warm', 'Spring, Summer, Autumn', 'NULL'),
(68, 'res/Products/Jumpers/MennaceStripedJumper', 'Mennace jumper in black stripe', 'Mennace', 2900, 'Jumper', 'Male', 'Relaxed', 'Black', 'Jumper', 'Stripe', 'Acrylic, Polyamide', 'Crew neck, Dropped shoulders', 'Casual, Lazy', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'All', 'NULL'),
(69, 'res/Products/Jumpers/ASOSBlueVJumper', 'ASOS DESIGN cotton v-neck jumper in denim blue', 'ASOS DESIGN', 1800, 'Jumper', 'Male', 'Regular', 'Blue', 'Jumper', 'Plain', 'Cotton', 'V neck, Long sleeve, Ribbed cuffs and hems', 'Outerwear, Formal', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(70, 'res/Products/Jumpers/ASOSKnittedMultiJumper', 'ASOS DESIGN knitted textured jumper in multi colou', 'ASOS DESIGN', 2500, 'Jumper', 'Male', 'Regular', 'Multi', 'Jumper', 'Textured', 'Cotton', 'Crew neck, Ribbed cuffs and hem', 'Casual, Lazy', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'All', 'NULL'),
(71, 'res/Products/Jumpers/BershkaTieDieJumper', 'Bershka jumper with tie die print in grey', 'Bershka', 2599, 'Jumper', 'Male', 'Regular', 'Grey', 'Jumper', 'Tie Die', 'Cotton', 'Crew neck, Ribbed trims', 'Casual, Outerwear', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'All', 'NULL'),
(72, 'res/Products/Bottoms/RiverIslandWhiteJeans', 'River Island Amelie skinny jeans in white', 'River Island', 4000, 'Bottoms', 'Female', 'Skinny', 'White', 'Jeans', 'Plain', 'Cotton, Polyester, Elastane', 'High rise, Belt loops, Concealed fly, Pockets', 'Casual, Outerwear', 'Sunny, Cold, Cloudy', 'All', 'NULL'),
(73, 'res/Products/Bottoms/StradSkinnyBlackJeans', 'Stradivarius super high wais skinny jean in black', 'Stradivarius', 1999, 'Bottoms', 'Female', 'Skinny', 'Black', 'Jeans', 'Plain', 'Cotton, Polyester, Viscose, Elastane', 'High rise waist, Concealed fly, Five pockets', 'Casual, Outerwear', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'All', 'NULL'),
(74, 'res/Products/Bottoms/BershkaBlueRippedJeans', 'Bershka ripped detail skinny jean in blue', 'Bershka', 1999, 'Bottoms', 'Female', 'Skinny', 'Blue', 'Jeans', 'Ripped', 'Cotton, Elastane', 'High rise, Concealed fly, Five pockets', 'Casual, Everyday', 'Sunny, Cloudy, Warm', 'Spring, Autumn', 'NULL'),
(75, 'res/Products/Bottoms/ArattaStripedShorts', 'Aratta relaxed stripe shorts with contrast tassle ', 'Aratta', 6500, 'Bottoms', 'Female', 'Relaxed', 'Pink', 'Shorts', 'Stripe', 'Polyester, Cotton', 'Metallic threadwork, Fully lined, Drawstring waist', 'Casual, Everyday, Lazy', 'Sunny, Warm', 'Summer', 'NULL'),
(76, 'res/Products/Bottoms/TommyJeanShorts', 'Tommy Jeans long line shorts raw hem', 'Tommy Hilfiger', 6500, 'Bottoms', 'Female', 'Regular', 'Blue', 'Shorts', 'Distressed', 'Cotton', 'Mid rise waist, Concealed fly, Functional pockets,', 'Casual, Everyday, Beach', 'Sunny, Warm', 'Summer', 'NULL'),
(77, 'res/Products/Bottoms/MissguidedPleatedShorts', 'Missguided pleated shorts co-ord in orange', 'Missguided', 2500, 'Bottoms', 'Female', 'Regular', 'Orange', 'Shorts', 'Pleated', 'Polyester', 'Mid rise waist, Belted detail', 'Casual, Outerwear', 'Sunny, Warm', 'Summer', 'NULL'),
(78, 'res/Products/Bottoms/VeroPinkLongSkirt', 'Vero Moda smudge print midi skirt', 'Vero Moda', 2900, 'Bottoms', 'Female', 'Midi', 'Pink', 'Skirt', 'Print', 'Polyester', 'Mid rise waist, Stretch back panel, Lettuce hem', 'Casual, Everyday, Beach', 'Warm, Cloudy, Sunny', 'Spring, Summer', 'NULL'),
(79, 'res/Products/Bottoms/ASOSBlackPolkaSkirt', 'ASOS DESIGN mini wrap skirt in polka dot print', 'ASOS DESIGN', 1800, 'Bottoms', 'Female', 'Regular', 'Black', 'Skirt', 'Polka dot', 'Viscose, Elastane', 'Elasticated waistband, Wrap front with tie detail', 'Casual, Outerwear', 'Sunny, Warm, Cloudy', 'All', 'NULL'),
(80, 'res/Products/Bottoms/ASOSPencilSkirt', 'ASOS DESIGN high waisted pencil skirt', 'ASOS DESIGN', 1800, 'Bottoms', 'Female', 'Bodycon', 'Camel', 'Skirt', 'Pencil', 'Viscose, Nylon, Elastane', 'High-rise waist, Zip back fastening', 'Outerwear, Evening', 'Sunny, Warm, Cloudy', 'Spring, Summer, Autumn', 'NULL'),
(81, 'res/Products/Bottoms/ASOSSequinTrouser', 'ASOS EDITION linear sequin trouser', 'ASOS EDITION', 10000, 'Bottoms', 'Female', 'Relaxed', 'Lilac grey', 'Trouser', 'Sequin', 'Cotton', 'High rise, Concealed fly', 'Outerwear, Evening', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(82, 'res/Products/Bottoms/AdidasStripeLegging', 'Adidas Originals adicolor three stripe leggings in', 'Adidas', 2800, 'Bottoms', 'Female', 'Bodycon', 'Black', 'Leggings', 'Stripe, Logo', 'Cotton, Elastane', 'High rise, Elasticated waistband', 'Active, Lazy, Casual', 'Cold, Wet, Windy, Sunny, Cloudy, Warm', 'Spring, Summer, Winter, Autumn', 'NULL'),
(83, 'res/Products/Bottoms/ASOSLeatherLeggings', 'ASOS DESIGN leather look leggings with elastic sli', 'ASOS DESIGN', 2200, 'Bottoms', 'Female', 'Bodycon', 'Black', 'Leggings', 'Leather', 'Polyester, Elastane', 'High rise, Elasticated inserts to waist', 'Outerwear, Evening', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(84, 'res/Products/Bottoms/WeekdaySweatpants', 'Weekday nylon cuffed joggers in beige', 'Weekday', 4500, 'Bottoms', 'Female', 'Regular', 'Beige', 'Joggers', 'Plain', 'Polyamide, Cotton', 'Stretch waistband, Fitted cuffs', 'Active, Casual', 'Sunny, Warm, Cold, Windy, Cloudy', 'Spring, Summer, Autumn, Winter', 'NULL'),
(85, 'res/Products/Bottoms/WarehouseTaperedTrouser', 'Warehouse tapered trousers with belt in pink', 'Warehouse', 3600, 'Bottoms', 'Female', 'Tapered', 'Pink', 'Trouser', 'Plain', 'Polyester, Elastane', 'High rise, Belted waist, Cropped length', 'Outerwear, Evening', 'All ', 'Spring, Summer, Autumn, Winter', 'NULL'),
(86, 'res/Products/Bottoms/PLTBeachTrousers', 'PrettyLittleThing wide leg beach trousers in geo p', 'PrettyLittleThing', 2500, 'Bottoms', 'Female', 'Relaxed', 'Multi', 'Trouser', 'Print', '\r\nPolyester', 'High-rise  waistband, Wide cut leg', 'Beach, Casual, Lazy', 'Sunny, Cloudy, Warm', 'Spring, Summer', 'NULL'),
(87, 'res/Products/Bottoms/SikSilkRippedWhiteJeans', 'Sik Silk skinny jeans in white', 'SikSilk', 5000, 'Bottoms', 'Male', 'Skinny', 'White', 'Jeans', 'Ripped', 'Cotton, Elastane', 'Regular rise, Button fly, Functional pockets, Logo', 'Casual, Outerwear', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'All', 'NULL'),
(88, 'res/Products/Bottoms/KOISlimJeans', 'Kings of Indigo John slim fit jeans in bright blue', 'Kings of Indigo', 13500, 'Bottoms', 'Male', 'Slim', 'Bright blue', 'Jeans', 'Plain', 'Cotton, Polyester, Elastane', 'Concealed fly, Functional pockets', 'Casual, Everyday', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(89, 'res/Products/Bottoms/NewLookBlackSkinnyJeans', 'New Look skinny jeans with knee rip in black wash', 'New Look', 2499, 'Bottoms', 'Male', 'Skinny', 'Black', 'Jeans', 'Ripped', 'Cotton, Elastane', 'Regular rise, Zip fly, Five pockets', 'Casual, Outerwear', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'All', 'NULL'),
(90, 'res/Products/Bottoms/ASOSGreySmartJeans', 'ASOS DESIGN smart skinny jeans in raw grey', 'ASOS DESIGN', 3000, 'Bottoms', 'Male', 'Skinny', 'Grey', 'Jeans', 'Plain', 'Cotton, Elastomultiester, Elastane', 'Regular rise, Zip fly, Functional pockets', 'Outerwear, Evening, Formal', 'Windy, Wet, Sunny, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(91, 'res/Products/Bottoms/BOSSChinoShorts', 'BOSS Schino slim fit shorts in beige', 'BOSS', 7900, 'Bottoms', 'Male', 'Slim', 'Beige', 'Shorts', 'Plain', 'Cotton, Elastane', 'Concealed fly, Functional pockets', 'Beach, Casual, Everyday', 'Sunny, Warm', '\r\nSpring, Summer', 'NULL'),
(92, 'res/Products/Bottoms/TimberlandSweatshorts', 'Timberland sweatshorts with print in black', 'Timberland', 4500, 'Bottoms', 'Male', 'Regular', 'Black', 'Shorts', 'Logo', 'Cotton, Polyester', 'Drawstring waistband, Side pockets', 'Casual, Active, Lazy', 'Sunny, Warm', 'Spring, Summer', 'NULL'),
(93, 'res/Products/Bottoms/LevisJeanShorts', 'Levi’s 502 tapered fit hemmed denim shorts in harb', 'Levis', 5000, 'Bottoms', 'Male', 'Tapered', 'Blue', 'Shorts', 'Washed', 'Cotton, Elastane', 'Concealed fly, Functional pockets', 'Casual, Everyday', 'Sunny, Warm', 'Spring, Summer', 'NULL'),
(94, 'res/Products/Bottoms/NikeGreySweatshorts', 'Nike Jersey Shorts In Grey 804419-063', 'Nike', 2200, 'Bottoms', 'Male', 'Regular', 'Grey', 'Shorts', 'Logo', 'Cotton', 'Drawstring waistband, Side pockets', 'Active, Casual, Lazy', 'Sunny, Warm', 'Spring, Summer', 'NULL'),
(95, 'res/Products/Bottoms/QuicksilverStripedSwimShorts', 'Quicksilver Everyday Grass Roots 17 inch board sh', 'Quicksilver', 5000, 'Bottoms', 'Male', 'Regular', 'Black', 'Shorts', 'Stripe, Logo', 'Polyester', 'Drawstring waistband, Mesh lining, Back pocket', 'Active, Beach', 'Sunny, Warm', 'Spring, Summer', 'NULL'),
(96, 'res/Products/Bottoms/ReplayRedSwimShorts', 'Replay logo swim shorts in burgundy', 'Replay', 4000, 'Bottoms', 'Male', 'Regular', 'Burgundy', 'Shorts', 'Logo', 'Polyester', 'Drawstring waistband, Mesh lining, Side pockets', 'Active, Beach, Swim', 'Sunny, Warm', 'Spring, Summer', 'NULL'),
(97, 'res/Products/Bottoms/MossSuitTrouser', 'Moss London slim suit trouser in navy linen with s', 'Moss London', 4900, 'Bottoms', 'Male', 'Slim', 'Navy', 'Trouser', 'Plain', 'Linen, Polyester, Viscose, Elastane', 'Belt loops, Side pockets', 'Formal, Outerwear', 'All', 'All', 'NULL'),
(98, 'res/Products/Bottoms/TwistedCheckTrouser', 'Twisted Tailor tapered crop suit trouser in grey s', 'Twisted Tailor', 6500, 'Bottoms', 'Male', 'Tapered', 'Grey', 'Trouser', 'Check', 'Polyester, Wool, Elastane', 'Concealed fy, Functional pockets, Cropped leg', 'Formal, Outerwear, Evening', 'All', 'All', 'NULL'),
(99, 'res/Products/Bottoms/DickiesBlackChinos', 'Dickies 872 work pant chino in slim fit ', 'Dickies', 4500, 'Bottoms', 'Male', 'Slim', 'Black', 'Chino', 'Plain', 'Polyester, Cotton', 'Concealed fly, Side pockets', 'Formal, Casual, Evening', 'All', 'All', 'NULL'),
(100, 'res/Products/Bottoms/AdidasBlackJoggers', 'Adidas Originals Superstar skinny joggers cuffed i', 'Adidas', 4500, 'Bottoms', 'Male', 'Skinny', 'Black', 'Joggers', 'Stripe, Logo', 'Polyester, Cotton', 'Functional pockets, Fitted cuffs', 'Lazy, Casual, Everyday, Active', 'Wet, Sunny, Windy, Cloudy, Cold, Warm', 'Spring, Summer, Autumn, Winter', 'NULL'),
(101, 'res/Products/Bottoms/NudieGreenChinos', 'Nudie Jeans Co Silm Adam chinos in bunker green', 'Nudie', 12000, 'Bottoms', 'Male', 'Slim', 'Green', 'Chino', 'Plain', 'Cotton, Elastane', 'Concealed fly, Side pockets', 'Formal, Casual, Outerwear', 'All', 'All', 'NULL'),
(102, 'res/Products/Coats/ASOSBoucleCoat', 'ASOS DESIGN boucle textured coat', 'ASOS DESIGN', 6500, 'Coat', 'Female', 'Regular', 'White', 'Boucle', 'Textured', 'Acrylic, Viscose, Cotton, Polyester', 'Crew neck, Open front, Frayed trims, Side pockets', 'Outerwear, Formal ', 'Cold, Cloudy', 'Spring, Summer, Autumn', 'NULL'),
(103, 'res/Products/Coats/WeekdayWhiteDenimCoat', 'Weekday cropped denim jacket with buttons in white', 'Weekday', 5500, 'Coat', 'Female', 'Relaxed, Cropped', 'White', 'Jacket', 'Plain', 'Cotton', 'Round neck, Dropped shoulders, Buttons placket', 'Casual, Everyday, Outerwear', 'Cold, Cloudy', 'Spring, Summer, Autumn', 'NULL'),
(104, 'res/Products/Coats/NewLookCheckCoat', 'New Look Check Tailored Coat', 'New Look', 2350, 'Coat', 'Female', 'Tailored', 'Brown', 'Coat', 'Check', 'Polyester, Acrylic, Viscose, Wool, Nylon, Cotton', 'Notch lapels, Button closure, Functional pockets', 'Formal, Evening, Outerwear', 'Cold, Cloudy', 'Spring, Summer, Winter', 'NULL'),
(105, 'res/Products/Coats/NoisyLeatherJacket', 'Noisy May faux leather jacket', 'Noisy May', 3800, 'Coat', 'Female', 'Regular', 'Black', 'Jacket', 'Leather', '\r\nPolyurethane, Polyester, Cotton', 'Mid-weight design, Fully lined, Notch lapels', 'Casual, Outerwear', 'Cold, Cloudy', 'Spring, Summer, Autumn', 'NULL'),
(106, 'res/Products/Coats/BershkaBeigeBlazer', 'Bershka longline linen double breasted blazer in b', 'Bershka', 2999, 'Coat', 'Female', 'Regular', 'Beige', 'Blazer', 'Plain', 'Ramie, Cotton', 'Notch lapels, Double-breasted design, Buttons', 'Formal, Outerwear, Casual', 'Sunny, Cloudy, Cold', 'Spring, Summer, Autumn', 'NULL'),
(107, 'res/Products/Coats/ASOSLongRaincoat', 'ASOS DESIGN raincoat with brushed check lining', 'ASOS DESIGN', 5500, 'Coat', 'Female', 'Regular', 'Blue', 'Raincoat', 'Check', 'Polyurethane, Polyester, Cotton, Viscose', 'Adjustable hood, Press stud fastening, Pockets', 'Everyday, Casual', 'Wet, Cold, Windy', 'Winter, Spring, Autumn', 'NULL'),
(108, 'res/Products/Coats/ASOSGreyCape', 'ASOS DESIGN plain cape in grey', 'ASOS DESIGN', 1800, 'Coat', 'Female', 'Oversized', 'Grey', 'Cape', 'Plain', 'Acrylic', 'Open front, Slip-on style, Tassel trims', 'Casual, Everyday, Lazy', 'Sunny, Cold, Cloudy', 'Spring, Summer', 'NULL'),
(109, 'res/Products/Coats/ASOSPinStripeBlazer', 'ASOS DESIGN white pinstripe suit blazer', 'ASOS DESIGN', 5500, 'Coat', 'Female', 'Regular', 'White', 'Blazer', 'Pin stripe', 'Polyester, Elastane', 'Peak lapel, Double-breasted opening, pockets', 'Formal, Evening, Outerwear', 'Sunny, Cloudy, Warm', 'All', 'NULL'),
(110, 'res/Products/Coats/ASOSSuedeJacket', 'ASOS WHITE suede belted jacket', 'ASOS DESIGN', 12000, 'Coat', 'Female', 'Regular', 'Brown', 'Jacket', 'leather', 'Real leather', 'Collar, Buttons placket, Belted waist, pockets', 'Casual, Formal, Outerwear', 'Cold, Windy, Cloudy', 'Spring, Autumn, Summer', 'NULL'),
(111, 'res/Products/Coats/ASOSParkaJacket', 'ASOS DESIGN parka with detachable faux fur liner', 'ASOS DESIGN', 7000, 'Coat', 'Female', 'Regular', 'Black', 'Parka', 'Plain', 'Cotton, Polyester, Modacrylic, Acrylic', 'Hood neck, Detachable faux fur trim, Zip fasteni', 'Casual, Everyday', 'Cold, Wet, Windy, Cloudy', 'Winter, Spring, Autumn', 'NULL'),
(112, 'res/Products/Coats/PimkieTailoredCoat', 'Pimkie tailored coat in pale blue', 'Pimkie', 4699, 'Coat', 'Female', 'Tailored', 'Blue', 'Coat', 'Plain', 'Polyester, Viscose, Wool', 'Notch lapels, Dropped shoulders, Buttons', 'Casual, Outerwear', 'Cold, Cloudy', 'Spring, Autumn', 'NULL'),
(113, 'res/Products/Coats/MonkieOversizedCoat', 'Monki oversized lightweight coat in khaki', 'Monki', 6000, 'Coat', 'Female', 'Oversized, Lightweight', 'Khaki', 'Coat', 'Plain', 'Cotton', 'Spread collar, Buttons fastening, pockets', 'Outerwear, Casual', 'Wet, Cloudy, Windy, Cold2', 'Spring, Summer, Autumn', 'NULL'),
(114, 'res/Products/Coats/Pull&BearRainMac', 'Pull&Bear contrast stitch rain mac with pockets in', 'PullAndBear', 2999, 'Coat', 'Female', 'Regular', 'Navy', 'Raincoat', 'Stitch', 'Polyurethane, Polyester', 'Zip front,  Drawstring hood and hem, pockets', 'Casual, Everyday', 'Wet, Cloudy, Windy', 'Spring, Summer, Autumn', 'NULL'),
(115, 'res/Products/Coats/ASOSPrintBlazer', 'ASOS DESIGN relaxed blazer in animal print', 'ASOS DESIGN', 1750, 'Coat', 'Female', 'Relaxed', 'Animal', 'Blazer', 'Print', 'Polyester', 'Notch lapels, Double button closure, Tie waist', 'Outerwear, Formal, Evening', 'Sunny, Warm, Cloudy', 'Spring, Summer', 'NULL'),
(116, 'res/Products/Coats/VilaTrenchcoat', 'Vila Trench Coat', 'Vila', 4800, 'Coat', 'Female', 'Regular', 'Beige', 'Trench Coat', 'Plain', 'Polyester', 'Fully lined, Epaulettes detail, Notch collar', 'Outerwear, Casual', 'Wet, Windy, Cold', 'Spring, Summer, Autumn, Winter', 'NULL'),
(117, 'res/Products/Coats/NudieWorkerJacket', 'Nudie Jeans Co Sten zip through worker jacket in w', 'Nudie', 15500, 'Coat', 'Male', 'Regular', 'Blue', 'Worker Jacket', 'Plain', 'Cotton', 'Point collar, Zip placket, Single chest pockets', 'Outerwear, Casual', 'Wet, Cloudy, Cold', 'Spring, Summer, Autumn', 'NULL'),
(118, 'res/Products/Coats/EspiritHoodieJacket', 'Espirit lightweight hooded jacket in navy colour b', 'Espirit', 5500, 'Coat', 'Male', 'Regular', 'Blue', 'Jacket', 'Colour block', 'Nylon, Polyester', 'Drawstring hood, Zip placket, Side pockets', 'Casual, Everyday', 'Wet, Cold, Warm, Cloudy', 'Spring, Summer, Autumn', 'NULL'),
(119, 'res/Products/Coats/Pull&BearQuiltedJacket', 'Pull&Bear lightweight overhead quilted jacket in n', 'PullAndBear', 2599, 'Coat', 'Male', 'Regular', 'Navy', 'Jacket', 'Quilted', 'Polyester, Nylon', 'Funnel collar, zip fastening, pockets', 'Casual, Active, Everyday', 'Cold, Cloudy, Windy', 'Winter, Spring, Autumn', 'NULL'),
(120, 'res/Products/Coats/ASOSHaringtonBlack', 'ASOS DESIGN muscle Harrington jersey jacket in bla', 'ASOS DESIGN', 2000, 'Coat', 'Male', 'Muscle', 'Black', 'Harrington', 'Plain', 'Cotton, Elastane', 'Baseball collar, Zip fastening, Pockets, cuffs', 'Outerwear, Casual, Everday', 'Windy, Cold, Cloudy', 'Spring, Summer, Autumn', 'NULL'),
(121, 'res/Products/Coats/ASOSDenimJacketBlack', 'ASOS DESIGN denim jacket with detachable borg coll', 'ASOS DESIGN', 3500, 'Coat', 'Male', 'Regular', 'Black', 'Jacket', 'Denim', 'Cotton', 'Detachable borg collar, Buttons, Pockets', 'Casual, Outerwear', 'Sunny, Cloudy, Cold, Windy', 'Spring, Summer, Autumn', 'NULL'),
(122, 'res/Products/Coats/EllesseSportJacket', 'Ellesse Ion overhead jacket with reflective logo i', 'Ellesse', 5000, 'Coat', 'Male', 'Regular', 'Black', 'Jacket', 'Reflective, Logo', 'Nylon', 'Funnel neck, Drawstring hood, zip opening, Pockets', 'Active, Casual, Everyday', 'Wet, Cold, Warm, Cloudy', 'Spring, Summer, Autumn', 'NULL'),
(123, 'res/Products/Coats/TwistedStoneWaistcoat', 'Twisted Tailor super skinny suit waistcoat in ston', 'Twisted Tailor', 5500, 'Coat', 'Male', 'Skinny', 'Stone grey', 'Waistcoat', 'Plain', 'Polyester, Viscose, Linen', 'Buttons, Contrast back, Adjustable cinch', 'Formal, Outerwear', 'Sunny, Warm, Cloudy', 'All', 'NULL'),
(124, 'res/Products/Coats/MossBoucleBlazer', 'Moss London slim blazer in gingham boucle', 'Moss London', 9900, 'Coat', 'Male', 'Slim', 'Blue', 'Blazer', 'Boucle', 'Polyester, Viscose', 'Peak lapels, buttons opening, Internal pocket, ', 'Formal, Outerwear', 'All', 'All', 'NULL'),
(125, 'res/Products/Coats/ASOSTrenchCoat', 'ASOS DESIGN shower resistant trench coat in black', 'ASOS DESIGN', 5000, 'Coat', 'Male', 'Regular', 'Black', 'Trench Coat', 'Plain', 'Polyester', 'Fully lined, Spread collar, Press, pockets', 'Outerwear, Casual, Everyday, Formal', 'Wet, Cloudy, Windy, Cold', 'Winter, Spring, Autumn', 'NULL'),
(126, 'res/Products/Coats/OhSoReissueJacket', 'Nike Full Zip Reissue Jacket In Red', 'Nike', 8500, 'Coat', 'Male', 'Regular', 'Red', 'Reissue Jacket', 'Stripe, Logo', 'Cotton, Nylon, Polyester, Elastane', 'Funnel neck, Zip fastening, Functional pockets', 'Active, Casual, Lazy', 'Cloudy, Cold, Windy', 'Winter, Spring, Autumn', 'NULL'),
(127, 'res/Products/Coats/ASOSBomberGrey', 'ASOS DESIGN Tall jersey bomber in light grey', 'ASOS DESIGN', 2000, 'Coat', 'Male', 'Regular', 'Grey', 'Bomber', 'Plain', 'Cotton, Elastane', 'Baseball collar, Zip placket, Side pockets, Ribbed', 'Casual, Everyday', 'Windy, Cold, Cloudy', 'Spring, Summer, Autumn', 'NULL'),
(128, 'res/Products/Coats/ReclaimedDenimJacket', 'Reclaimed Vintage oversized denim jacket in black', 'Reclaimed', 4500, 'Coat', 'Male', 'Oversized', 'Black', 'Jacket', 'Denim', 'Cotton', 'Point collar, Buttons placket, Functional pockets', 'Outerwear, Casual', 'Cloudy, Cold', 'Spring, Summer, Autumn, Winter', 'NULL'),
(129, 'res/Products/Coats/GymKingTrackJacket', 'Gym King jacket in white retro shell', 'Gym King', 6500, 'Coat', 'Male', 'Regular', 'White', 'Track Jacket', 'Retro, Logo', 'Polyester', 'Funnel neck, Zip fastening, Functional pockets', 'Active, Casual', 'Wet, Cold, Windy, Cloudy', 'Spring, Winter, Autumn', 'NULL'),
(130, 'res/Products/Coats/TommyGreenBomber', 'Tommy Hilfiger icon bomber with large sleeve logo ', 'Tommy Hilfiger', 25000, 'Coat', 'Male', 'Relaxed', 'Green', 'Bomber', 'Logo', 'Polyester, Polyamide', 'Baseball collar, Zip opening, MA 1 pockets', 'Casual, Everyday, Outerwear', 'Sunny, Cold, Cloudy, Windy', 'All', 'NULL'),
(131, 'res/Products/Coats/RipCamoFanorak', 'RIPNDIP Nermcamo Fanorak jacket in green', 'Rip N Dip', 10000, 'Coat', 'Male', 'Regular', 'Yellow', 'Fanorak', 'Desert nerm camo', 'Polyester', 'Fixed hood, Zip placket, Front pockets', 'Casual, Everyday', 'Wet, Cold, Windy, Cloudy', 'All', 'NULL'),
(132, 'res/Products/Underwear/LindexUnderwearSet', 'Lindex Ella M Paris embroidered bandeau bralette &', 'Lindex', 3300, 'Underwear', 'Female', 'Unknown', 'White', 'Set', 'Bandaeu', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(133, 'res/Products/Underwear/WolfUnderwearSet', 'Wolf & Whistle lace cutout contrast bra & brief se', 'Wolf And Whistle', 38000, 'Underwear', 'Female', 'Unknown', 'Pink', 'Set', 'Cutout', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(134, 'res/Products/Underwear/NewLookUnderwearSet', 'New Look balcony bra & Brief set', 'New Look', 1898, 'Underwear', 'Female', 'Unknown', 'Pink', 'Set', 'Balcony', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(135, 'res/Products/Underwear/SavageUnderwearSet', 'Savage x Fenty all over logo triangle bralet & tho', 'Save x Fenty', 5400, 'Underwear', 'Female', 'Unknown', 'Grey', 'Set', 'Print', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(136, 'res/Products/Underwear/TuttiBodysuit', 'Tutti Rougette Alicia Fuller Bust lace and mesh mi', 'Tutti Rouge', 2400, 'Underwear', 'Female', 'Unknown', 'Black', 'Bodysuit', 'Lace', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(137, 'res/Products/Underwear/ASOSFishnetUnderwearSet', 'ASOS DESIGN fuller bust Agnes chunky strap & fishn', 'ASOS DESIGN', 1800, 'Underwear', 'Female', 'Unknown', 'Pink', 'Set', 'Fishnet', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(138, 'res/Products/Underwear/ASOSRedLaceUnderwearSet', 'ASOS DESIGN Roxy lace triangle bra, thong and susp', 'ASOS DESIGN', 3200, 'Underwear', 'Female', 'Unknown', 'Red', 'Set', 'Lace', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(139, 'res/Products/Underwear/NikeTrainingBra', 'Nike Training Swoosh sports bra with cut outs in b', 'Nike', 3500, 'Underwear', 'Female', 'Unknown', 'Blue', 'Bra', 'Plain', 'Unknown', 'Unknown', 'Active', 'Sunny, Warm', 'Spring, Summer', NULL),
(140, 'res/Products/Underwear/SummersLaceUnderwearSet', 'Ann Summers Neva guipure lace strapping bra and br', 'Ann Summers', 3200, 'Underwear', 'Female', 'Unknown', 'Black', 'Set', 'Lace', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(141, 'res/Products/Underwear/KleinBodyUnderwearSet', 'Calvin Klein Body Unlined Triangle & Thong Lingeri', 'Calvin Klein', 4800, 'Underwear', 'Female', 'Unknown', 'White', 'Set', 'Print', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(142, 'res/Products/Underwear/WeekdayStripeBra', 'Weekday sheer stripe cut out triangle bra in sage ', 'Weekday', 1200, 'Underwear', 'Female', 'Unknown', 'Green', 'Bra', 'Stripe', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(143, 'res/Products/Underwear/TommyLaceThong', 'Tommy Hilfiger Flag Core Lace thong in yucca mint', 'Tommy Hilfiger', 2000, 'Underwear', 'Female', 'Unknown', 'Mint green', 'Thong', 'Lace', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(144, 'res/Products/Underwear/PumaCasualBra', 'Puma iconic casual bralette in navy', 'Puma', 1700, 'Underwear', 'Female', 'Unknown', 'Navy', 'Bralet', 'Logo', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(145, 'res/Products/Underwear/ASOSUnderwireBodysuit', 'ASOS DESIGN Verlee high shine underwire legging sh', 'ASOS DESIGN', 2800, 'Underwear', 'Female', 'Unknown', 'Khaki', 'Bodysuit', 'High shine', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(146, 'res/Products/Underwear/SpanxThong', 'Spanx undie-tectable thong', 'Spanx', 2400, 'Underwear', 'Female', 'Unknown', 'Beige', 'Thong', 'Plain', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', NULL),
(147, 'res/Products/Underwear/KleinAbstractBoxer', 'Calvin KleinID microfibre abstract print trunks in', 'Calvin Klein', 2300, 'Underwear', 'Male', 'Tight', 'Black', 'Trunk', 'Abstract', 'Nylon, Elastane', 'Branded waistband, Form-fitting design', 'Casual, Everyday', 'Unknown', 'Unknown', NULL),
(148, 'res/Products/Underwear/ASOSBlackBoxer', 'ASOS DESIGN jersey boxer in black', 'ASOS DESIGN', 500, 'Underwear', 'Male', 'Loose', 'Black', 'Boxer', 'Plain', 'Cotton', 'Elasticated waistband, Non-functional button fly', 'Casual, Everyday', 'Unknown', 'Unknown', NULL),
(149, 'res/Products/Underwear/KleinDitsyBoxer', 'Calvin Klein ditsy print woven boxers in black', 'Calvin Klein', 2500, 'Underwear', 'Male', 'Loose', 'Black', 'Boxer', 'Print', 'Cotton', 'Branded stretch waistband', 'Casual, Everyday', 'Unknown', 'Unknown', NULL),
(150, 'res/Products/Underwear/BOSSLeafTrunk', 'BOSS leaf print trunks in grey', 'BOSS', 2100, 'Underwear', 'Male', 'Tight', 'Grey', 'Trunk', 'Print', 'Cotton, Elastane', 'Branded waistband, Form-fitting design', 'Casual, Everyday', 'Unknown', 'Unknown', NULL),
(151, 'res/Products/Underwear/KleinModernTrunk', 'Calvin Klein Modern FLX trunks in white', 'Calvin Klein', 2000, 'Underwear', 'Male', 'Tight', 'White', 'Trunk', 'Logo', 'Cotton, Elastane', 'Branded waistband, Form-fitting design', 'Casual, Everyday', 'Unknown', 'Unknown', NULL),
(152, 'res/Products/Underwear/KleinModernBriefs', 'Calvin Klein Modern FLX briefs in dark grey', 'Calvin Klein', 1900, 'Underwear', 'Male', 'Tight', 'Grey', 'Briefs', 'Logo', 'Cotton, Elastane', 'Elasticated waistband, Form-fitting design', 'Casual, Everyday', 'Unknown', 'Unknown', NULL),
(153, 'res/Products/Underwear/ArmaniStripeBriefs', 'Emporio Armani stripe briefs in blue', 'Emporio Armani', 3300, 'Underwear', 'Male', 'Tight', 'Blue', 'Briefs', 'Stripe', 'Polyamide, Elastane', 'Branded stretch waistband, Form-fitting design', 'Casual, Everyday', 'Unknown', 'Unknown', NULL),
(154, 'res/Products/Underwear/DieselRainbowJockstrap', 'Diesel logo rainbow jockstrap in pink', 'Diesel', 2200, 'Underwear', 'Male', 'Tight', 'Pink', 'Jockstrap', 'Logo', 'Cotton, Elastane, Nylon, Polyester', 'Branded waistband, Form fitting design', 'Unknown', 'Unknown', 'Unknown', NULL),
(155, 'res/Products/Underwear/BOSSLogoTrunks', 'BOSS logo trunks in navy', 'BOSS', 2500, 'Underwear', 'Male', 'Tight', 'Navy', 'Trunk', 'Logo', 'Viscose, Elastane', 'Branded waistband, Form-fitting design', 'Casual, Everyday', 'Unknown', 'Unknown', NULL),
(156, 'res/Products/Underwear/KleinMonogramTrunks', 'Calvin Klein Monogram neppy trunks in charcoal', 'Calvin Klein', 2600, 'Underwear', 'Male', 'Tight', 'Charcoal', 'Trunk', 'Neppy', 'Cotton, Elastane', 'Branded waistband, Form-fitting design', 'Casual, Everyday', 'Unknown', 'Unknown', NULL),
(157, 'res/Products/Underwear/HUGOPrintTrunks', 'HUGO print trunks', 'BOSS', 2000, 'Underwear', 'Male', 'Tight', 'Multi', 'Trunk', 'Print', 'Cotton, Elastane', 'Branded waistband, Form-fitting design', 'Casual, Everyday', 'Unknown', 'Unknown', NULL),
(158, 'res/Products/Underwear/SmithStripeTrunks', 'Paul Smith stripe trunk in multi', 'Paul Smith', 2700, 'Underwear', 'Male', 'Tight', 'Multi', 'Trunk', 'Stripe', 'Cotton, Spandex', 'Branded waistband, Form-fitting design', 'Casual,Everyday', 'Unknown', 'Unknown', NULL),
(159, 'res/Products/Underwear/ASOSCatTrunks', 'ASOS DESIGN trunk wth cat in sunglasses back print', 'ASOS DESIGN', 400, 'Underwear', 'Male', 'Tight', 'White', 'Trunk', 'Print', 'Polyester, Elastane', 'Stretch waistband, Form fitting design', 'Casual, Everyday', 'Unknown', 'Unknown', NULL),
(160, 'res/Products/Underwear/AAPEPrintBoxers', 'AAPE By A Bathing Ape All Over Logo Print Boxers I', 'AAPE', 2500, 'Underwear', 'Male', 'Loose', 'Black', 'Boxer', 'Print', 'Cotton', 'Branded, stretch waistband', 'Casual, Everyday', 'Unknown', 'Unknown', NULL),
(161, 'res/Products/Underwear/ASOSMeshBoxer', 'ASOS DESIGN trunks in wide mesh fabric', 'ASOS DESIGN', 500, 'Underwear', 'Male', 'Tight', 'Black', 'Trunk', 'Mesh', 'Nylon, Elastane, Cotton, Polyester', 'Low rise, Stretch waistband, Form-fitting design', 'Casual Everyday', 'Unknown', 'Unknown', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD UNIQUE KEY `ID` (`ID`),
  ADD UNIQUE KEY `ID_2` (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `ID` int(255) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=162;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
